Add slack messages

diff --git a/.github/workflows/update-helm-charts-index.yml b/.github/workflows/update-helm-charts-index.yml
--- a/.github/workflows/update-helm-charts-index.yml
+++ b/.github/workflows/update-helm-charts-index.yml
@@ -30,6 +30,7 @@ jobs:
             exit 1
           fi
       - name: update helm-charts index
+        id: update
         env:
           # FIXME: waypoint team to input token
           GH_TOKEN: ${{ secrets.HELM_CHARTS_GITHUB_TOKEN }}
@@ -39,5 +40,28 @@ jobs:
             --ref main \
             -f SOURCE_TAG="${{ github.ref_name }}" \
             -f SOURCE_REPO="${{ github.repository }}"
+      - name: Prepare Slack Notification
+        if: always()
+        run: |
+          case "${{ steps.update.conclusion }}" in
+            failure)
+              echo "SLACK_MESSAGE=:red_circle: The vault-helm charts index update failed." >> "$GITHUB_ENV"
+              echo "SLACK_BLOCK_COLOR=ed5c5c" >> "$GITHUB_ENV"
+              ;;
+            success)
+              echo "SLACK_MESSAGE=:tada: The vault-helm charts index update succeeded." >> "$GITHUB_ENV"
+              echo "SLACK_BLOCK_COLOR=1cbf43" >> "$GITHUB_ENV"
+              ;;
+          esac
+      - name: Send Slack Notification
+        # note: this will skip Slack notification if the job is skipped or cancelled.
+        if: ${{ (success() || failure()) && env.SLACK_MESSAGE != '' }}
+        uses: ./.github/actions/slack-status
+        with:
+          block-color: ${{ env.SLACK_BLOCK_COLOR }}
+          message: ${{ env.SLACK_MESSAGE }}
+          run-url: ${{ env.RUN_URL }}
+          # FIXME: waypoint team to input token
+          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
 permissions:
   contents: read
